server:
  port: 10086
  
spring:
  application:
    name: user-service-config
  cloud:
    config:
      server:
        git:
          uri: https://github.com/fyrichy/springcloud-config.git